package prog2.model;

import prog2.vista.CentralUBException;
import java.io.Serializable;
import java.util.List;
import java.util.ArrayList;

public class Dades implements InDades, Serializable {
    // Constants
    public final static long VAR_UNIF_SEED = 123;
    public final static float GUANYS_INICIALS = 0;
    public final static float PREU_UNITAT_POTENCIA = 1;
    public final static float PENALITZACIO_EXCES_POTENCIA = 250;

    // Atributs
    private final VariableUniforme variableUniforme;
    private float insercioBarres;
    private final Reactor reactor;
    private final SistemaRefrigeracio sistemaRefrigeracio;
    private final GeneradorVapor generadorVapor;
    private final Turbina turbina;
    private final Bitacola bitacola;
    private int dia;
    private float guanysAcumulats;

    public Dades() {
        this.variableUniforme = new VariableUniforme(VAR_UNIF_SEED);
        this.insercioBarres = 100; // 100% per defecte
        this.reactor = new Reactor();
        this.sistemaRefrigeracio = new SistemaRefrigeracio();
        this.generadorVapor = new GeneradorVapor();
        this.turbina = new Turbina();
        this.bitacola = new Bitacola();
        this.dia = 1;
        this.guanysAcumulats = GUANYS_INICIALS;

        // Configuracio inicial dels components
        this.reactor.desactiva();
        this.generadorVapor.activa();
        this.turbina.activa();
        this.sistemaRefrigeracio.desactiva();

        // Afegir 4 bombes refrigerants
        for (int i = 0; i < 4; i++) {
            // Assuming BombaRefrigerant constructor correctly handles variableUniforme
            BombaRefrigerant bomba = new BombaRefrigerant(i, this.variableUniforme);
            this.sistemaRefrigeracio.afegirBomba(bomba);
        }
    }

    //IMPLEMENTACIO InDades:

    @Override
    public float getInsercioBarres() {
        return this.insercioBarres;
    }

    @Override
    public void setInsercioBarres(float grau) throws CentralUBException {
        if (grau < 0 || grau > 100) {
            throw new CentralUBException("Error: El grau d'insercio ha d'estar entre 0% i 100%");
        }
        this.insercioBarres = grau;
    }

    public int getDia() {
        return this.dia;
    }

    @Override
    public void activaReactor() throws CentralUBException {
        if (this.reactor.getTemperatura() > Reactor.TEMP_MAXIMA) {
            throw new CentralUBException("Error: No es pot activar el reactor. Temperatura massa alta (>1000C)");
        }
        this.reactor.activa();
    }

    @Override
    public void desactivaReactor() {
        this.reactor.desactiva();
    }

    @Override
    public Reactor mostraReactor() {
        return this.reactor;
    }

    @Override
    public void activaBomba(int id) throws CentralUBException {
        if (id < 0 || id >= this.sistemaRefrigeracio.getBombes().size()) { // Use getBombes().size() for robustness
            throw new CentralUBException("Error: L'ID de la bomba ha d'estar entre 0 i " + (this.sistemaRefrigeracio.getBombes().size() - 1));
        }
        this.sistemaRefrigeracio.getBombes().get(id).activa();
    }

    @Override
    public void desactivaBomba(int id) {
        if (id < 0 || id >= this.sistemaRefrigeracio.getBombes().size()) {
            System.err.println("Error: L'ID de la bomba ha d'estar entre 0 i " + (this.sistemaRefrigeracio.getBombes().size() - 1));
            return;
        }

        this.sistemaRefrigeracio.getBombes().get(id).desactiva();
    }


    public void activaSistemaRefrigeracio() throws CentralUBException {
        this.sistemaRefrigeracio.activa();
    }


    public void desactivaSistemaRefrigeracio() {
        this.sistemaRefrigeracio.desactiva();
    }


    @Override
    public SistemaRefrigeracio mostraSistemaRefrigeracio() {
        return this.sistemaRefrigeracio;
    }

    /**
     * Calculates the total electrical power generated by the central.
     * This method correctly chains the output calculations from Reactor -> Cooling System -> Steam Generator -> Turbine.
     * @return The total generated electrical power.
     */
    @Override
    public float calculaPotencia() {
        if (!this.reactor.getActivat()) return 0.0f; // If reactor is off, no power is generated

        float outputReactor = this.reactor.calculaOutput(this.insercioBarres);
        float outputRefrigeracio = this.sistemaRefrigeracio.calculaOutput(outputReactor);
        float outputGenerador = this.generadorVapor.calculaOutput(outputRefrigeracio);
        return this.turbina.calculaOutput(outputGenerador);
    }

    @Override
    public float getGuanysAcumulats() {
        return this.guanysAcumulats;
    }

    @Override
    public PaginaEstat mostraEstat() {
        // Recalculate outputs for the state page to reflect current conditions and chain
        float reactorOutput = this.reactor.getActivat() ? this.reactor.calculaOutput(this.insercioBarres) : 0;
        float coolingOutput = this.sistemaRefrigeracio.calculaOutput(reactorOutput); // Heat extracted
        float generatorInputTemp = reactorOutput - coolingOutput; // Heat reaching generator
        float generatorOutputSteamTemp = this.generadorVapor.calculaOutput(generatorInputTemp); // Steam temp out of generator
        float turbinaOutputPower = this.turbina.calculaOutput(generatorOutputSteamTemp); // Electrical power out of turbine

        return new PaginaEstat(
                this.dia,
                this.insercioBarres,
                reactorOutput,
                coolingOutput,
                generatorOutputSteamTemp,
                turbinaOutputPower
        );
    }


    @Override
    public Bitacola mostraBitacola() {
        return this.bitacola;
    }

    @Override
    public List<PaginaIncidencies> mostraIncidencies() {
        return this.bitacola.getIncidencies();
    }

    @Override
    public Bitacola finalitzaDia(float demandaPotencia) throws CentralUBException {
        // 1. Actualitza economia
        PaginaEconomica paginaEconomica = actualitzaEconomia(demandaPotencia);

        // 2. Genera pagina d'estat
        PaginaEstat paginaEstat = mostraEstat(); // This now uses the actual chain for state snapshot

        // 3. Refrigerar reactor
        refrigeraReactor();

        // 4. Revisar components
        PaginaIncidencies paginaIncidencies = new PaginaIncidencies(this.dia);
        revisaComponents(paginaIncidencies);

        // 5. Actualitzar dia
        this.dia++;

        // 6. Afegir a bitacola
        this.bitacola.afegeixPagina(paginaEconomica);
        this.bitacola.afegeixPagina(paginaEstat);
        if (!paginaIncidencies.getIncidencies().isEmpty()) {
            this.bitacola.afegeixPagina(paginaIncidencies);
        }


        return this.bitacola;
    }

    //METODES PRIVATS:

    private PaginaEconomica actualitzaEconomia(float demandaPotencia) {
        float potenciaGenerada = calculaPotencia(); // This is the total generated power
        float percentatgeSatisfet = (demandaPotencia > 0)
                ? (Math.min(potenciaGenerada, demandaPotencia) / demandaPotencia) * 100
                : 0;

        float beneficis = Math.min(potenciaGenerada, demandaPotencia) * PREU_UNITAT_POTENCIA;
        float penalitzacio = (potenciaGenerada > demandaPotencia) ? PENALITZACIO_EXCES_POTENCIA : 0;
        float costOperatiu = getCostOperatiuTotal();

        float guanys = beneficis - penalitzacio - costOperatiu;
        this.guanysAcumulats += guanys;

        return new PaginaEconomica(
                this.dia, demandaPotencia, potenciaGenerada, percentatgeSatisfet,
                beneficis, penalitzacio, costOperatiu, this.guanysAcumulats
        );
    }

    private void refrigeraReactor() {
        float calorExtreta = this.sistemaRefrigeracio.calculaOutput(this.reactor.getTemperatura());
        float novaTemperatura = this.reactor.getTemperatura() - calorExtreta;
        this.reactor.setTemperatura(Math.max(novaTemperatura, 25)); // Minim 25C
    }

    private void revisaComponents(PaginaIncidencies paginaIncidencies) {
        this.reactor.revisa(paginaIncidencies);
        this.sistemaRefrigeracio.revisa(paginaIncidencies);
    }

    public float getCostOperatiuTotal() {
        return this.reactor.getCostOperatiu() +
                this.sistemaRefrigeracio.getCostOperatiu() +
                this.generadorVapor.getCostOperatiu() +
                this.turbina.getCostOperatiu();
    }

    /**
     * Genera un valor aleatorio para la demanda de potencia eléctrica diaria.
     * Este valor representa la "necesidad" externa de energía para el día.
     * **IMPORTANT: Verify the actual method name in your VariableUniforme.java class!**
     * It's most likely 'generaValor()' or 'nextFloat()' or 'getValor()'.
     * @return La demanda de potencia generada (float entre 1000 y 2000).
     */
    public float generaDemandaPotenciaDiaria() {
        // Reverted to 'generaValor()'. PLEASE VERIFY THIS METHOD NAME IN YOUR VARIABLEUNIFORME.JAVA!
        return 1000f + (this.variableUniforme.seguentValor() * 1000f);
    }
}